FROM python:3.13-slim
ENV PATH="/usr/local/bin:$PATH" 
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN chmod +x docker-entrypoint.sh 
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["exec python -m uvicorn main_webhook_server:app --host 0.0.0.0 --port $PORT"]